name: rock_quiz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  #splash screen, quiz presentation
  assets:
    - assets/img/
    - assets/questions/
    - assets/
  #Raleway import
  fonts:
    - family: 'Poppins300'
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: 'Poppins400'
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: 'Poppins500'
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: 'Poppins600'
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
